const KEY="royal21_free_roam_v1";
const defaultState={name:"Royal Player",balance:10000,xp:0,level:1,wins:0,losses:0,plays:0,streak:0,bestStreak:0,achievements:[],lastBonus:null,theme:"royal",sound:true,inventory:[]};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaultState);
let bet=10, current=null, roulettePick=null, dicePick=null;
const canvas=document.getElementById("world"),ctx=canvas.getContext("2d"),modal=document.getElementById("modal");
const keys={}; let last=performance.now(), toastTimer=null;
const player={x:550,y:560,r:15,speed:205,dir:0};
const W=1100,H=650;
const machines=[
 {x:145,y:185,w:86,h:62,label:"ROYAL SLOTS",icon:"🎰",game:"slots"},
 {x:275,y:185,w:86,h:62,label:"BLACKJACK",icon:"🃏",game:"blackjack"},
 {x:405,y:185,w:86,h:62,label:"ROULETTE",icon:"🎡",game:"roulette"},
 {x:535,y:185,w:86,h:62,label:"LUCKY DICE",icon:"🎲",game:"dice"},
 {x:665,y:185,w:86,h:62,label:"SLOT X",icon:"7️⃣",game:"slots"},
 {x:795,y:185,w:86,h:62,label:"HIGH ROLLER",icon:"💎",game:"roulette"}
];
const interactables=[...machines,{x:955,y:505,w:100,h:72,label:"PRIZE COUNTER",icon:"🎁",game:"shop"},{x:120,y:505,w:100,h:72,label:"PLAYER DESK",icon:"👤",game:"profile"}];
const walls=[{x:35,y:95,w:1030,h:20},{x:35,y:95,w:20,h:500},{x:1045,y:95,w:20,h:500},{x:35,y:575,w:1030,h:20},{x:35,y:350,w:1030,h:14},{x:520,y:95,w:20,h:150},{x:520,y:430,w:20,h:165}];
function fmt(n){return Math.floor(n).toLocaleString()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));hud()}
function hud(){document.getElementById("balance").textContent=fmt(state.balance);document.getElementById("level").textContent=state.level;document.getElementById("xpbar").style.width=((state.xp%500)/5)+"%"}
function toast(t){const el=document.getElementById("toast");el.textContent=t;el.className="show";clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className="",2200)}
function gainXP(n){const old=state.level;state.xp+=n;state.level=1+Math.floor(state.xp/500);if(state.level>old)toast("⭐ Level "+state.level+" reached!");save()}
function unlock(name){if(!state.achievements.includes(name)){state.achievements.push(name);toast("🏆 "+name+" unlocked");save()}}
function win(xp=25){state.wins++;state.plays++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);gainXP(xp);if(state.wins===1)unlock("First Win");if(state.streak>=5)unlock("Hot Streak");save()}
function loss(xp=8){state.losses++;state.plays++;state.streak=0;gainXP(xp);save()}
function validBet(){const input=document.getElementById("customBet");const b=input&&input.value?Math.floor(+input.value):bet;if(!Number.isFinite(b)||b<1||b>state.balance){toast("Pick a valid virtual-chip bet.");return null}if(b>=1000)unlock("High Roller");return b}
function betUI(){return `<div class="bet-row"><span class="muted">BET</span>${[10,50,100,500,1000].map(n=>`<button class="bet ${n===bet?"active":""}" onclick="setBet(${n},this)">${n}</button>`).join("")}<input id="customBet" class="bet custom" type="number" min="1" placeholder="Custom"></div>`}
function setBet(n,el){bet=n;document.querySelectorAll(".bet").forEach(x=>x.classList.remove("active"));if(el)el.classList.add("active")}
function closeModal(){modal.innerHTML="";current=null;roulettePick=null;dicePick=null}
function modalShell(title,sub,body,extra=""){modal.innerHTML=`<div class="modal-card ${extra}"><div class="modal-head"><div><div class="eyebrow">ROYAL 21 • ${title.toUpperCase()}</div><h1>${title}</h1><p class="muted">${sub}</p></div><button class="close" onclick="closeModal()">×</button></div>${body}</div>`}
function slots(){current="slots";modalShell("Royal Slots","A classic three-reel machine. Virtual chips only.",`${betUI()}<div class="reels"><div id="r1" class="reel">🍒</div><div id="r2" class="reel">💎</div><div id="r3" class="reel">7️⃣</div></div><div class="actions"><button class="btn primary" onclick="spin()">SPIN</button></div><div class="game-result" id="slotResult">Match symbols to win.</div>`)}
const syms=["🍒","🍋","🔔","💎","7️⃣","⭐","🍀"];
function spin(){const b=validBet();if(b===null)return;state.balance-=b;save();["r1","r2","r3"].forEach(id=>document.getElementById(id)?.classList.add("spin"));setTimeout(()=>{const a=[0,0,0].map(()=>syms[Math.floor(Math.random()*syms.length)]);["r1","r2","r3"].forEach((id,i)=>{const e=document.getElementById(id);if(e){e.textContent=a[i];e.classList.remove("spin")}});let mult=0;if(a.every(x=>x==="7️⃣")){mult=25;unlock("Lucky Seven")}else if(a.every(x=>x==="💎"))mult=12;else if(a.every(x=>x==="⭐"))mult=10;else if(a.every(x=>x==="🍀"))mult=8;else if(a[0]===a[1]&&a[1]===a[2])mult=5;else if(a[0]===a[1]||a[1]===a[2]||a[0]===a[2])mult=2;const r=document.getElementById("slotResult");if(mult){const p=b*mult;state.balance+=p;win(35);r.className="game-result win";r.textContent=`🎉 ${a.join(" ")} — ${fmt(p)} chips (${mult}×)`;if(state.balance>=20000)unlock("Chip Collector")}else{loss();r.className="game-result lose";r.textContent=`${a.join(" ")} — no match`}},550)}
function makeDeck(){const d=[];for(const s of ["♠","♥","♦","♣"])for(const r of ["A","2","3","4","5","6","7","8","9","10","J","Q","K"])d.push({s,r});return d.sort(()=>Math.random()-.5)}
function cardVal(cs){let n=0,a=0;for(const c of cs){if(c.r==="A"){n+=11;a++}else n+=["J","Q","K"].includes(c.r)?10:+c.r}while(n>21&&a){n-=10;a--}return n}
function card(c,hidden=false){return `<div class="card ${hidden?"hidden-card":(["♥","♦"].includes(c.s)?"red":"")}">${hidden?"♠":c.r+c.s}</div>`}
let bj={};
function blackjack(){current="blackjack";bj={p:[],d:[],deck:[],active:false,wager:0};modalShell("Blackjack","Beat the dealer without going over 21.",`${betUI()}<div class="hand"><h3>DEALER <span id="dv"></span></h3><div id="dealerCards" class="cards"></div></div><div class="hand"><h3>YOU <span id="pv"></span></h3><div id="playerCards" class="cards"></div></div><div class="actions"><button class="btn primary" onclick="deal()">DEAL</button><button class="btn secondary" onclick="hit()">HIT</button><button class="btn secondary" onclick="stand()">STAND</button><button class="btn secondary" onclick="dbl()">DOUBLE</button></div><div id="bjResult" class="game-result">Deal a hand.</div>`)}
function renderBJ(){if(!bj.p.length)return;document.getElementById("playerCards").innerHTML=bj.p.map(c=>card(c)).join("");document.getElementById("dealerCards").innerHTML=bj.d.map((c,i)=>bj.active&&i===1?card(c,true):card(c)).join("");document.getElementById("pv").textContent=cardVal(bj.p);document.getElementById("dv").textContent=bj.active?cardVal([bj.d[0]]):cardVal(bj.d)}
function deal(){if(bj.active)return;const b=validBet();if(b===null)return;state.balance-=b;const d=makeDeck();bj={p:[d[0],d[1]],d:[d[2],d[3]],deck:d.slice(4),active:true,wager:b};save();renderBJ();if(cardVal(bj.p)===21)finishBJ("blackjack")}
function hit(){if(!bj.active)return;bj.p.push(bj.deck.pop());renderBJ();if(cardVal(bj.p)>21)finishBJ("bust")}
function stand(){if(!bj.active)return;while(cardVal(bj.d)<17)bj.d.push(bj.deck.pop());finishBJ("stand")}
function dbl(){if(!bj.active||state.balance<bj.wager){toast("Not enough chips to double.");return}state.balance-=bj.wager;bj.wager*=2;bj.p.push(bj.deck.pop());renderBJ();if(cardVal(bj.p)>21)finishBJ("bust");else stand()}
function finishBJ(type){bj.active=false;const p=cardVal(bj.p),d=cardVal(bj.d),r=document.getElementById("bjResult");let good=false,msg="";if(type==="blackjack"){state.balance+=bj.wager*2.5;good=true;msg="🃏 BLACKJACK — 2.5× payout";unlock("Blackjack")}else if(p>21){msg="Bust — dealer wins."}else if(d>21||p>d){state.balance+=bj.wager*2;good=true;msg="🎉 You beat the dealer!"}else if(p===d){state.balance+=bj.wager;state.plays++;msg="Push — bet returned."}else msg="Dealer wins.";if(type!=="blackjack"&&p!==d){good?win(35):loss()}else if(type==="blackjack"){win(50)}else{save()}renderBJ();r.className="game-result "+(good?"win":"lose");r.textContent=msg}
const reds=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
function roulette(){current="roulette";roulettePick=null;modalShell("Royal Roulette","Pick red, black, zero, or an exact number.",`${betUI()}<div class="wheel-wrap"><div class="pointer">▼</div><div id="wheel" class="wheel"><div id="wn" class="wheel-center">?</div></div></div><div class="choice-grid"><button class="choice" onclick="pickR('red',this)">🔴 RED · 2×</button><button class="choice" onclick="pickR('black',this)">⚫ BLACK · 2×</button><button class="choice" onclick="pickR('zero',this)">🟢 ZERO · 14×</button></div><div class="number-grid">${Array.from({length:37},(_,i)=>`<button class="num" onclick="pickR(${i},this)">${i}</button>`).join("")}</div><div class="actions"><button class="btn primary" onclick="spinR()">SPIN WHEEL</button></div><div id="rr" class="game-result">Choose a bet.</div>`)}
function pickR(p,el){roulettePick=p;document.querySelectorAll(".choice,.num").forEach(x=>x.classList.remove("selected"));el.classList.add("selected")}
function spinR(){if(roulettePick===null){toast("Choose a roulette bet first.");return}const b=validBet();if(b===null)return;state.balance-=b;save();const n=Math.floor(Math.random()*37),color=n===0?"zero":reds.has(n)?"red":"black",wheel=document.getElementById("wheel");wheel.style.transform=`rotate(${360*5+n*9.73}deg)`;setTimeout(()=>{document.getElementById("wn").textContent=n;const m=roulettePick===n?35:roulettePick===color?(color==="zero"?14:2):0,r=document.getElementById("rr");if(m){const p=b*m;state.balance+=p;win(30);r.className="game-result win";r.textContent=`🎉 ${n} ${color} — ${fmt(p)} chips`}else{loss();r.className="game-result lose";r.textContent=`${n} ${color} — no win`}},2500)}
function dice(){current="dice";dicePick=null;modalShell("Lucky Dice","Guess low or high, then roll.",`${betUI()}<div id="diceFace" class="dice-face">🎲</div><div class="choice-grid"><button id="lo" class="choice" onclick="dicePick='low';this.classList.add('selected');document.getElementById('hi').classList.remove('selected')">LOW · 1–3</button><button id="hi" class="choice" onclick="dicePick='high';this.classList.add('selected');document.getElementById('lo').classList.remove('selected')">HIGH · 4–6</button></div><div class="actions"><button class="btn primary" onclick="roll()">ROLL</button></div><div id="dr" class="game-result">Make a prediction.</div>`)}
function roll(){if(!dicePick){toast("Choose high or low.");return}const b=validBet();if(b===null)return;state.balance-=b;save();const n=1+Math.floor(Math.random()*6),good=(dicePick==="low"&&n<=3)||(dicePick==="high"&&n>=4);document.getElementById("diceFace").textContent=["⚀","⚁","⚂","⚃","⚄","⚅"][n-1];const r=document.getElementById("dr");if(good){const p=Math.floor(b*1.8);state.balance+=p;win(20);r.className="game-result win";r.textContent=`🎉 Rolled ${n} — +${fmt(p)} chips`}else{loss();r.className="game-result lose";r.textContent=`Rolled ${n} — lost ${fmt(b)} chips`}}
function profile(){current="profile";const prog=(state.xp%500)/5;modalShell("Player Profile","Your progress, achievements, and identity.",`<div class="profile-grid"><div class="profile-stat"><b>${fmt(state.balance)}</b><span>CHIPS</span></div><div class="profile-stat"><b>${state.level}</b><span>LEVEL</span></div><div class="profile-stat"><b>${state.wins}</b><span>WINS</span></div><div class="profile-stat"><b>${state.plays}</b><span>ROUNDS</span></div></div><p><b>${state.name}</b> • ${state.xp%500}/500 XP</p><div class="xp" style="width:100%;height:7px"><div style="width:${prog}%"></div></div><div class="actions"><button class="btn secondary" onclick="editName()">EDIT NAME</button><button class="btn secondary" onclick="dailyBonus()">DAILY BONUS</button></div><h3>🏆 Achievements</h3><div class="achievement-list">${ach("First Win","Win any game","🎉",state.wins>=1)}${ach("Hot Streak","Win 5 in a row","🔥",state.bestStreak>=5)}${ach("Lucky Seven","Hit triple 7","7️⃣",state.achievements.includes("Lucky Seven"))}${ach("Blackjack","Get a natural 21","🃏",state.achievements.includes("Blackjack"))}${ach("High Roller","Bet 1,000+","👑",state.achievements.includes("High Roller"))}${ach("Chip Collector","Reach 20,000","💎",state.balance>=20000)}</div>`)}
function ach(n,d,i,on){return `<div class="achievement ${on?"":"locked"}"><b>${i} ${n}</b><span>${d}${on?" • UNLOCKED":" • LOCKED"}</span></div>`}
function editName(){const n=prompt("Display name:",state.name);if(n&&n.trim()){state.name=n.trim().slice(0,20);save();profile()}}
function dailyBonus(){const today=new Date().toDateString();if(state.lastBonus===today){toast("🎁 Daily bonus already claimed today.");return}const reward=500+state.level*50;state.balance+=reward;state.lastBonus=today;gainXP(50);toast("🎁 +"+fmt(reward)+" chips");profile()}
function shop(){current="shop";const items=[{n:"Gold Crown",e:"👑",c:1500},{n:"Lucky Duck",e:"🦆",c:2500},{n:"Diamond Chip",e:"💎",c:5000}];modalShell("Prize Counter","Spend virtual chips on collectible trophies.",`<div class="prizes">${items.map((x,i)=>`<div class="prize"><div class="emoji">${x.e}</div><h3>${x.n}</h3><div class="muted">${fmt(x.c)} chips</div><button class="btn primary" onclick="buyPrize(${i},${x.c},'${x.n}')">BUY</button></div>`).join("")}</div>`,"shop")}
function buyPrize(i,c,n){if(state.inventory.includes(n)){toast("You already own that prize.");return}if(state.balance<c){toast("Not enough chips.");return}state.balance-=c;state.inventory.push(n);save();toast("🏆 Added "+n+" to your collection");shop()}
function interact(o){if(o.game==="slots")slots();else if(o.game==="blackjack")blackjack();else if(o.game==="roulette")roulette();else if(o.game==="dice")dice();else if(o.game==="profile")profile();else if(o.game==="shop")shop()}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function circleRectCollide(x,y,r,rect){const cx=Math.max(rect.x,Math.min(x,rect.x+rect.w)),cy=Math.max(rect.y,Math.min(y,rect.y+rect.h));return Math.hypot(x-cx,y-cy)<r}
function move(dt){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(!dx&&!dy){return}const len=Math.hypot(dx,dy);dx/=len;dy/=len;player.dir=Math.atan2(dy,dx);let nx=player.x+dx*player.speed*dt,ny=player.y+dy*player.speed*dt;nx=Math.max(55,Math.min(W-55,nx));ny=Math.max(130,Math.min(H-40,ny));let blocked=false;for(const wall of walls)if(circleRectCollide(nx,ny,player.r+2,wall))blocked=true;if(!blocked){player.x=nx;player.y=ny}}
function nearest(){let best=null,bd=75;for(const o of interactables){const d=distance(player,o);if(d<bd){best=o;bd=d}}return best}
function updateInteraction(){const o=nearest(),box=document.getElementById("interaction");if(!o){box.classList.add("hidden");return}box.classList.remove("hidden");document.getElementById("interactionTitle").textContent=o.label;document.getElementById("interactionText").textContent=o.game==="shop"?"Spend chips / view prizes":"Press E to play"}
function roundedRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}
function drawFloor(){ctx.fillStyle="#141216";ctx.fillRect(0,0,W,H);ctx.fillStyle="#242028";ctx.fillRect(35,95,1030,500);ctx.fillStyle="#19161d";ctx.fillRect(55,125,990,220);ctx.fillStyle="#201c23";ctx.fillRect(55,364,990,210);ctx.strokeStyle="#473e49";ctx.lineWidth=2;ctx.strokeRect(35,95,1030,500);for(let x=60;x<1040;x+=42){ctx.strokeStyle="#2c2730";ctx.beginPath();ctx.moveTo(x,120);ctx.lineTo(x,570);ctx.stroke()}for(let y=125;y<575;y+=42){ctx.strokeStyle="#29252d";ctx.beginPath();ctx.moveTo(50,y);ctx.lineTo(1050,y);ctx.stroke()}ctx.fillStyle="#8d6c35";ctx.fillRect(35,340,1030,4);ctx.fillStyle="#0d0b0f";ctx.fillRect(470,115,160,90);ctx.fillStyle="#a17b38";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText("ROYAL 21",550,160);ctx.font="9px system-ui";ctx.fillStyle="#81776d";ctx.fillText("FREE ROAM FLOOR",550,178)}
function drawMachines(){for(const m of machines){ctx.save();ctx.fillStyle="#09080b99";roundedRect(ctx,m.x+5,m.y+7,m.w,m.h,9);ctx.fillStyle="#211a20";roundedRect(ctx,m.x,m.y,m.w,m.h,9);ctx.strokeStyle="#6e542b";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#0d0c10";roundedRect(ctx,m.x+9,m.y+8,m.w-18,34,6);ctx.font="23px system-ui";ctx.textAlign="center";ctx.fillText(m.icon,m.x+m.w/2,m.y+33);ctx.fillStyle="#e1bd69";ctx.font="bold 8px system-ui";ctx.fillText(m.label,m.x+m.w/2,m.y+53);ctx.restore()}}
function drawFurniture(){ctx.fillStyle="#6b4d28";roundedRect(ctx,82,405,170,70,12);ctx.fillStyle="#2a1718";roundedRect(ctx,92,415,150,50,8);ctx.fillStyle="#b18b47";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText("LOUNGE",167,445);ctx.fillStyle="#684c2a";roundedRect(ctx,740,410,190,58,12);ctx.fillStyle="#171116";roundedRect(ctx,750,420,170,38,8);ctx.fillStyle="#b18b47";ctx.fillText("VIP LOUNGE",835,444);for(const o of interactables.slice(6)){ctx.fillStyle="#1c171d";roundedRect(ctx,o.x-o.w/2,o.y-o.h/2,o.w,o.h,10);ctx.strokeStyle="#9b7733";ctx.stroke();ctx.font="25px system-ui";ctx.textAlign="center";ctx.fillText(o.icon,o.x,o.y+2);ctx.fillStyle="#d4b568";ctx.font="bold 8px system-ui";ctx.fillText(o.label,o.x,o.y+25)}}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.shadowColor="#000";ctx.shadowBlur=12;ctx.fillStyle="#d7a94e";ctx.beginPath();ctx.arc(0,0,player.r+3,0,Math.PI*2);ctx.fill();ctx.fillStyle="#19151b";ctx.beginPath();ctx.arc(0,-2,player.r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#e8d6b0";ctx.beginPath();ctx.arc(0,-10,7,0,Math.PI*2);ctx.fill();ctx.fillStyle="#3b2a20";ctx.beginPath();ctx.arc(0,-13,7,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle="#e0bd63";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,8);ctx.lineTo(Math.cos(player.dir)*13,8+Math.sin(player.dir)*13);ctx.stroke();ctx.restore()}
function drawLabels(){ctx.textAlign="center";ctx.font="bold 9px system-ui";ctx.fillStyle="#82786d";ctx.fillText("ARCADE ROW",550,130);ctx.fillText("LOUNGE",167,500);ctx.fillText("PRIZE COUNTER",955,548);ctx.fillText("PLAYER DESK",120,548)}
function render(){drawFloor();drawMachines();drawFurniture();drawLabels();drawPlayer()}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;if(!modal.innerHTML)move(dt);render();updateInteraction();requestAnimationFrame(loop)}
window.addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys[e.key]=true;if(e.key.toLowerCase()==="e"&&!modal.innerHTML){const o=nearest();if(o)interact(o)}if(e.key==="Escape"&&modal.innerHTML)closeModal()});window.addEventListener("keyup",e=>keys[e.key]=false);
document.getElementById("helpBtn").onclick=()=>modalShell("How to Play","The casino is now a place you move around in.",`<div class="game-result"><b>WASD / Arrow Keys</b> — walk around<br><br><b>E</b> — enter the nearby machine, desk, or prize counter<br><br><b>ESC</b> — leave a game<br><br>Walk up to a cabinet instead of clicking through menus. Everything uses virtual chips only.</div>`);
document.getElementById("soundBtn").onclick=()=>{state.sound=!state.sound;document.getElementById("soundBtn").textContent=state.sound?"🔊":"🔇";save()};
hud();document.getElementById("soundBtn").textContent=state.sound?"🔊":"🔇";requestAnimationFrame(loop);
